version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    networks:
      - cvbuilder
    volumes:
      - mongo_data:/data/db
    command: ["--replSet", "rs0", "--bind_ip_all"]

  mongo-init:
    image: mongo:6.0
    depends_on:
      - mongodb
    networks:
      - cvbuilder
    entrypoint: [ "/bin/bash", "-c", "sleep 5 && mongosh --host mongodb --authenticationDatabase admin --eval 'rs.initiate({_id: \"rs0\", members: [{_id: 0, host: \"mongodb:27017\"}]})' || true" ]

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - cvbuilder
    volumes:
      - redis_data:/data

  jenkins:
    image: jenkins/jenkins:lts-jdk17
    container_name: jenkins
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    user: root

networks:
  cvbuilder:
    driver: bridge

volumes:
  jenkins_home:
    driver: local
  mongo_data:
  redis_data: