package com.bsu.cvbuilder.annotation.metrics;

import io.prometheus.client.CollectorRegistry;
import io.prometheus.client.Counter;
import io.prometheus.client.Gauge;
import io.prometheus.client.Summary;
import org.springframework.stereotype.Component;

import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;

@Component
public class PrometheusMetrics {

    private static final String DEFAULT_HELP = "autogenerated";

    private final Map<String, Gauge> gauges = new ConcurrentHashMap<>();
    private final Map<String, Counter> counters = new ConcurrentHashMap<>();
    private final Map<String, Summary> summaries = new ConcurrentHashMap<>();
    
    private final Map<String, Summary> latencyCollectors = new ConcurrentHashMap<>();
    private final Map<String, Counter> errorCollectors = new ConcurrentHashMap<>();

    private final CollectorRegistry registry;

    public PrometheusMetrics(CollectorRegistry registry) {
        this.registry = registry;
    }

    public TimerContext startTimer(String metricName, String className, String methodName, String context) {
        String normalizedName = metricName.toLowerCase();
        
        String cls = (className != null && !className.isEmpty()) ? className : "-";
        String mtd = (methodName != null && !methodName.isEmpty()) ? methodName : "-";
        String ctx = (context != null && !context.isEmpty()) ? context : "-";

        ensureLatencyAndErrorCollectors(normalizedName);

        Summary summary = latencyCollectors.get(normalizedName);
        
        Summary.Timer timer = summary.labels(cls, mtd, ctx, "call").startTimer();

        return new TimerContext(timer, normalizedName, cls, mtd, ctx);
    }

    public void collectGauge(String metricName, String context, double value) {
        String name = metricName.toLowerCase();
        Gauge gauge = gauges.computeIfAbsent(name, k -> 
            Gauge.build()
                 .name(k)
                 .help(DEFAULT_HELP)
                 .labelNames("context")
                 .register(registry)
        );
        gauge.labels(context).set(value);
    }

    public void collectCounter(String metricName, String context, double value) {
        String name = metricName.toLowerCase();
        Counter counter = counters.computeIfAbsent(name, k -> 
            Counter.build()
                   .name(k)
                   .help(DEFAULT_HELP)
                   .labelNames("context")
                   .register(registry)
        );
        counter.labels(context).inc(value);
    }

    public void collectSummary(String metricName, String context, double value) {
        String name = metricName.toLowerCase();
        Summary summary = summaries.computeIfAbsent(name, k -> 
            Summary.build()
                   .name(k)
                   .help(DEFAULT_HELP)
                   .labelNames("context")
                   .register(registry)
        );
        summary.labels(context).observe(value);
    }

    private void ensureLatencyAndErrorCollectors(String metricName) {
        String[] labelNames = new String[]{"class", "method", "context", "event"};

        latencyCollectors.computeIfAbsent(metricName, k -> 
            Summary.build()
                   .name(k)
                   .help(DEFAULT_HELP)
                   .labelNames(labelNames)
                   .register(registry)
        );

        errorCollectors.computeIfAbsent(metricName, k -> 
            Counter.build()
                   .name(k + "_error")
                   .help(DEFAULT_HELP)
                   .labelNames(labelNames)
                   .register(registry)
        );
    }


    public class TimerContext implements AutoCloseable {
        private final Summary.Timer timer;
        private final String metricName;
        private final String cls;
        private final String mtd;
        private final String ctx;

        public TimerContext(Summary.Timer timer, String metricName, String cls, String mtd, String ctx) {
            this.timer = timer;
            this.metricName = metricName;
            this.cls = cls;
            this.mtd = mtd;
            this.ctx = ctx;
        }

        public void recordError(String errorType) {
            Counter errorCounter = errorCollectors.get(metricName);
            if (errorCounter != null) {
                errorCounter.labels(cls, mtd, ctx, errorType).inc();
            }
        }

        @Override
        public void close() {
            timer.observeDuration();
        }
    }
}