spring:
  application:
    name: cvbuilder
  config:
    import: optional:file:.env[.properties]
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  cache:
    type: redis
    redis:
      time-to-live: 1800000 # 30m
      cache-null-values: false
      key-prefix: "cvbuilder:"
      use-key-prefix: true
  ai:
    chat:
      memory:
        repository:
          mongo:
            ttl: 0
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: llama3.1:8b
      embedding:
        options:
          model: nomic-embed-text

  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      authentication-database: admin
      database: cvbuilder
      auto-index-creation: true
    redis:
      repositories:
        enabled: false
      host: 127.0.0.1
      port: 6379
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 2
          max-wait: -1ms
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope: user:email, read:user
  mail:
    host: smtp.gmail.com
    port: 587
    username: mmfask2024@gmail.com
    password: syvg ndjv wvdb tjlp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
server:
  port: 8888

app:
  volk:
    enabled: false
  minio:
    url: ${MINIO_URL:http://127.0.0.1:9000}
    bucket: ${MINIO_BUCKET:file-storage}
    access-key: ${MINIO_ACCESS_KEY:Q3AM3UQ867SPQQA43P2F}
    secret-key: ${MINIO_SECRET_KEY:zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG}
  telegram:
    enabled: true
    token: ${TELEGRAM_BOT_TOKEN_API}
    chat-id: ${TELEGRAM_BOT_CHAT_ID}
    url: ${TELEGRAM_BOT_URL}
  twilio:
    enabled: false
    account-sid: ${TWILIO_ACCOUNT_SID:}
    auth-token: ${TWILIO_AUTH_TOKEN:}
    phone-number: ${TWILIO_PHONE_NUMBER:}
  ai:
    prompts-flow-path: "classpath:/prompt/flow/*.txt"
    prompts-path: "classpath:/prompt/*.txt"
  limit:
    max-messages: 20 # 20 messages per 1 day
    messages-ban-duration: 1 # 1 day
  schedule:
    limit-period: "0 0 * * * *"
  cache:
    verification: 300 # seconds
    ttl: 30
    prefix: "cvbuild::"
  security:
    super-user-email: ${SUPER_USER_EMAIL}
    super-user-password: ${SUPER_USER_PASSWORD}
    oauth-redirect-url: "http://localhost:3000"
    allowed-origins: "http://localhost:3000"
    allowed-methods: "*"
    allowed-headers: "*"
    allow-credentials: true
    oauth2:
      enabled: true
    refresh-secret: ${JWT_REFRESH_SECRET}
    access-secret: ${JWT_ACCESS_SECRET}
    access-lifetime: 56400000
    refresh-lifetime: 90400000
    access-max-age-cookie: 3600
    refresh-max-age-cookie: 604800
    decode-signature: ${DECODE_SIGNATURE}
  chat:
    max-messages: 25
    temperature: 0.3
    topp: 0.7
    expansion-topp: 0.4
    expansion-temperature: 0.1
    extraction-temperature: 0.2
    memory-max-messages: 10
    stop-condition: "###INTERVIEW_COMPLETED###"
  prompt:
    base-prefix: /templates/prompt
    base-extension: .txt
    expansion: ${app.prompt.base-prefix}/expansion${app.prompt.base-extension}
    extractor: ${app.prompt.base-prefix}/extractor${app.prompt.base-extension}
    final-phase: ${app.prompt.base-prefix}/final${app.prompt.base-extension}
    interviewer: ${app.prompt.base-prefix}/interviewer${app.prompt.base-extension}
  analyzer:
    user-agent: ${USER_AGENT}
    trust-urls:
      - "rabota.by"
  volk-model: ${VOLK_MODEL}

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
  prometheus:
    metrics:
      export:
        enabled: true
  tracing:
    enabled: true
    sampling:
      probability: 1.0

logging:
  file:
    name: logs/app.log
  level:
    com.bsu.cvbuilder.service: info
